package com.udemy.scala.programming_in_depth.classesDemo

case class Car(name: String, model: String)
{
  var carName = name
  val carModel = model

  def printDetails(): Unit = {
    println(s"Car Name is: $carName and Car Model is: $carModel")
  }
}

object CaseClassDemoA{
  def main(args: Array[String]): Unit = {
    val bmw = Car("BMW", "550") // No need for "new", since "apply" method is auto-generated(CC)
    bmw.printDetails()
    bmw.carName = "B.M.W"
    bmw.printDetails()
    // bmw.name = "B.M.W" // Constructor parameter is val by default

    bmw match {
      case Car(a, b) => println(a); println(b)  // CC autogenerate unapply method, used for matching
    }

    // Autogenerated copy method
    val mercedes = bmw.copy("Mercedes")
    mercedes.printDetails()

    // equals and hashcode method
    println(bmw == mercedes)

    // toString method is autoimplemented
    println(bmw)
  }
}
